# -*- coding: utf-8 -*-
"""Alura_Introdução_a_Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iCnL06nCdwCfB1SK6X1zxEPqa7wVk6Ub
"""

a = 10
b = 5
soma = a + b

print(soma)

'samuel'

nome = 'samuel'

idade = 38

print('meu nome é samuel e tenho 38 anos')

print(f'meu nome é {nome} e tenho {idade} anos')

idade = 39

def saudacao():
  nome = input('Qual seu nome? ')
  print(f'Olá {nome}')

saudacao()

"""# Criando minha primeira função"""

def nome_completo():
 primeiro_nome = input('Qual seu primeiro nome? ')
 sobrenome = input('Qual seu sobrenome? ')
 nome_inteiro = primeiro_nome + ' ' + sobrenome
 print(nome_inteiro)

nome_completo()
SAMUEL OLIVEIRA SATURNO

def saudacao():
  nome = input("Qual é seu nome? ")
  print(f"Olá {nome} ")

saudacao

"""# Parâmetro"""

nome = 'Letícia'

def saudacao_com_parametros (nome_da_pessoa):
  print(f'Olá {nome_da_pessoa}')

saudacao_com_parametros (nome)

nome = 'Astrogildo'

"""# Condicional"""

idade = 15


def verificar_permissão_para_dirigir (idade):
  if idade >= 18:
    print('Tem permissão para dirigir!')
  else:
    print('Não tem permissão para dirigir!')

verificar_permissão_para_dirigir (idade)

def verificar_permissão_para_dirigir_sem_parametro ():
  idade = input('Qual sua idade? ')
  idade = int(idade)

  if idade >= 18:
    print('Tem permissão para dirigir!')
  else:
    print('Não tem permissão para dirigir!')

verificar_permissão_para_dirigir_sem_parametro ()





"""# Função velocidade"""

def velocidade(espaco, tempo):
  v = espaco / tempo
  print(f'velocidade: {v} m/s')

velocidade(100, 20)

def habilitacao():
   idade = input('Qual sua idade? ')
   idade = int(idade)

  if idade >= 18:
    print('pode tirar habitação')

  else:
    print('Aguarde mais um pouco!')

habilitacao()

def habilitacao():
 idade = input('Qual sua idade? ')
 idade = int(idade)
 if idade >= 18:
   print('Pode tirar habilitação')

 elif idade <= 16 or idade >= 14:
   tempo = 18 - idade
   print(f'Calma... espere {tempo} ano(s) para tirar habilitação')

 else:
   print('nao pode tirar habilitação')

habilitacao()



"""# Loop"""

idades = [18, 22, 15, 50]

idades

def verificar_permissão_para_dirigir (idade):
  if idade >= 18:
    print(f'{idade} anos de idades, Tem permissão para dirigir!')
  else:
    print(f'{idade} anos de idades, Não Tem permissão para dirigir!')

for idade in idades:
  verificar_permissão_para_dirigir(idade)

def verificar_permissão_para_dirigir(idades):
  for idade in idades:
    if idade >= 18:
      print(f'{idade} anos de idades, Tem permissão para dirigir!')
    else:
      print(f'{idade} anos de idades, Não Tem permissão para dirigir!')

verificar_permissão_para_dirigir(idades)



"""# Boleano"""

idade = 18
idade >= 18

idade >=2

idade >= 50

permissoes = []
idades = [17, 14, 4]

def verificar_se_pode_dirigir(idades, permissoes):
  for idade in idades:
    if idade >= 18:
      permissoes.append(True)
    else: 
      permissoes.append(False)

verificar_se_pode_dirigir(idades, permissoes)

permissoes

for permissao in permissoes:
  if permissao == True:
    print('Pode dirigir')
  else:
    print('Não pode dirigir')

lista = ['tiago', 'josé', 'Maria', 'pedro']

lista

lista[2]

lista[1:3]

lista[ :3]

frase_alura = [' Digitais', ' e ', 'Negócios ', 'de ', 'Tecnologia ', 'Cursos ']

frase_alura[-1] + frase_alura[-3] + frase_alura[-2] + frase_alura[0] + frase_alura[-5] + frase_alura[-4]

a=2

if a < 2:
 a = a + 1
else:
 a = a + 2
if a < 4:
 a = a - 4
else:
 a = a + 6

a

"""# Tipos de lista """

lista = ['Samuel', 38, True, 3.14]
for elemento in lista:
  print(f'O elemento{elemento} é do tipo:', type(elemento))



"""# Import"""

from random import randrange, seed

randrange(0,11)

notas_matemática = []

for notas in range(8):
  notas_matemática.append(randrange(0,11))

notas_matemática

len(notas_matemática)



"""# matplolib"""

import matplotlib.pyplot as plt

x = list(range(1, 9))
y = notas_matemática

plt.plot(x, y, marker='o')
plt.title('Notas de matemática')
plt.xlabel ('Provas')
plt.ylabel ('Notas')
plt.show()

import matplotlib.pyplot as plt

notas_matematica = ['Matemática',8,7,6,6,7,7,8,10]
notas_portugues = ['Português',9,9,9,8,5,6,8,5]
notas_geografia = ['Geografia',10,10,6,7,7,7,8,7]

notas = [notas_matematica, notas_portugues, notas_geografia]

for nota in notas:
 x = list(range(1, 9))
 y = nota[1:]
 plt.plot(x, y, marker='o')
 plt.xlabel('Provas')
 plt.ylabel('Notas')
 plt.show()

for nota in notas:
 x = list(range(1, 10))
 y = nota
 plt.plot(x, y, marker='o')
 plt.xlabel('Provas')
 plt.ylabel('Notas')
 plt.title(nota[0])
 plt.show()